/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaChallenges;

import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testArrayShift(){
      int[] arr = {2,5,6,8};
      int expectedOutput = 5;
      int actualOutput = ArrayShift.insertShiftArray(arr,5).length;
      assertEquals("Array sizes should match",expectedOutput,actualOutput);
    }
}
